# Auto-generated by propcheck — do not edit manually
# Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/python/calculator.py
# Generated: 2026-03-26T12:59:53.256Z

import sys
import os
import json
from pathlib import Path

# Add target directory to Python path
sys.path.insert(0, str(Path(__file__).parent / "../../test-fixtures/python"))

from hypothesis import given, settings, assume
from hypothesis import strategies as st
import calculator as target

MAX_EXAMPLES = 1000

# prop_001: Addition is commutative
# Category: equivalence
# Evidence: add(a, b) takes two numbers and returns their sum
def test_prop_001():
    try:
        @given(a=st.integers(min_value=-1000, max_value=1000), b=st.integers(min_value=-1000, max_value=1000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a, b):
            assert target.add(a, b) == target.add(b, a)
        inner()
        print(json.dumps({"propertyId": "prop_001", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_001", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_001", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

# prop_002: Zero is identity element
# Category: boundary
# Evidence: adding zero should not change the value
def test_prop_002():
    try:
        @given(a=st.integers(min_value=-1000, max_value=1000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a):
            assert target.add(a, 0) == a
        inner()
        print(json.dumps({"propertyId": "prop_002", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_002", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_002", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

if __name__ == "__main__":
    test_prop_001()
    test_prop_002()