# Auto-generated by propcheck — do not edit manually
# Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/python/calculator.py
# Generated: 2026-03-27T00:45:06.539Z

import sys
import os
import json
from pathlib import Path

# Add target directory to Python path
sys.path.insert(0, str(Path(__file__).parent / "../../test-fixtures/python"))

from hypothesis import given, settings, assume
from hypothesis import strategies as st
import calculator as target

MAX_EXAMPLES = 1000

# prop_001: Addition is commutative
# Category: equivalence
# Evidence: Addition: a + b == b + a for all integers
def test_prop_001():
    try:
        @given(a=st.integers(min_value=-10000, max_value=10000), b=st.integers(min_value=-10000, max_value=10000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a, b):
            assert target.add(a, b) == target.add(b, a)
        inner()
        print(json.dumps({"propertyId": "prop_001", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_001", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_001", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

# prop_002: Zero is identity element for addition
# Category: boundary
# Evidence: a + 0 = a; additive identity
def test_prop_002():
    try:
        @given(a=st.integers(min_value=-10000, max_value=10000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a):
            assert target.add(a, 0) == a
        inner()
        print(json.dumps({"propertyId": "prop_002", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_002", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_002", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

# prop_003: Addition is associative
# Category: equivalence
# Evidence: (a + b) + c == a + (b + c); associativity of addition
def test_prop_003():
    try:
        @given(a=st.integers(min_value=-1000, max_value=1000), b=st.integers(min_value=-1000, max_value=1000), c=st.integers(min_value=-1000, max_value=1000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a, b, c):
            assert target.add(target.add(a, b), c) == target.add(a, target.add(b, c))
        inner()
        print(json.dumps({"propertyId": "prop_003", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_003", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_003", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

# prop_004: Division by 1 returns the original number
# Category: boundary
# Evidence: a / 1 = a; division by unity identity
def test_prop_004():
    try:
        @given(a=st.floats(allow_nan=False, allow_infinity=False, min_value=-10000, max_value=10000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(a):
            assert target.divide(a, 1) == a
        inner()
        print(json.dumps({"propertyId": "prop_004", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_004", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_004", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

# prop_005: Division of zero always returns zero
# Category: boundary
# Evidence: 0 / b = 0 for any non-zero b
def test_prop_005():
    try:
        @given(b=st.floats(allow_nan=False, allow_infinity=False, min_value=0.001, max_value=10000))
        @settings(max_examples=MAX_EXAMPLES)
        def inner(b):
            assert target.divide(0, b) == 0
        inner()
        print(json.dumps({"propertyId": "prop_005", "status": "passed", "iterations": MAX_EXAMPLES}))
    except AssertionError as e:
        print(json.dumps({"propertyId": "prop_005", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))
    except Exception as e:
        # Parse Hypothesis falsifying example from error message
        msg = str(e)
        print(json.dumps({"propertyId": "prop_005", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))

if __name__ == "__main__":
    test_prop_001()
    test_prop_002()
    test_prop_003()
    test_prop_004()
    test_prop_005()