// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/cart.ts
// Generated: 2026-03-26T11:24:12.673Z

const fc = require("fast-check");
const target = require("../../test-fixtures/typescript/cart");

const numRuns = 1000;

// prop_001: Result is non-negative
// Category: boundary
// Evidence: prices should never be negative after discount
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      fc.double({ min: 0, max: 100, noNaN: true }),
      (price, discount) => {
        const result = target.applyDiscount(price, discount);
        return target.applyDiscount(price, discount) >= 0;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  const counterexample = e.counterexample ?? null;
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: e.message ?? String(e),
    shrinkSteps: e.numShrinks ?? 0
  }));
}

// prop_002: Result does not exceed original price
// Category: monotonic
// Evidence: discount should reduce or maintain price, never increase
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      fc.double({ min: 0, max: 100, noNaN: true }),
      (price, discount) => {
        const result = target.applyDiscount(price, discount);
        return target.applyDiscount(price, discount) <= price;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  const counterexample = e.counterexample ?? null;
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: e.message ?? String(e),
    shrinkSteps: e.numShrinks ?? 0
  }));
}

// prop_003: Zero discount returns original price
// Category: boundary
// Evidence: zero discount should not change the price
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      (price) => {
        const result = target.applyDiscount(price);
        return target.applyDiscount(price, 0) === price;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_003", status: "passed", iterations: numRuns }));
} catch (e) {
  const counterexample = e.counterexample ?? null;
  console.log(JSON.stringify({
    propertyId: "prop_003",
    status: "failed",
    counterexample,
    errorMessage: e.message ?? String(e),
    shrinkSteps: e.numShrinks ?? 0
  }));
}
