// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/cart-buggy.ts
// Generated: 2026-03-27T01:11:32.709Z

const fc = require("C:/Users/allenenli/claude-code-projects/propcheck/node_modules/fast-check/lib/cjs/fast-check.js");
const target = require("../../test-fixtures/typescript/cart-buggy.ts");

const numRuns = 1000;

// prop_001: Discounted price should be non-negative for valid inputs
// Category: boundary
// Evidence: @param discount - Discount percentage (0-100); prices should not go negative
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      fc.double({ min: 0, max: 200, noNaN: true }),
      (price, discount) => {
        return target.applyDiscount(price, discount) >= 0;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_002: Discount should not increase the price when discount is positive
// Category: monotonic
// Evidence: Discount reduces price; @param discount - Discount percentage (0-100)
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      fc.double({ min: -50, max: 200, noNaN: true }),
      (price, discount) => {
        return discount >= 0 ? target.applyDiscount(price, discount) <= price : true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_003: Zero discount returns original price unchanged
// Category: boundary
// Evidence: Zero discount means no change to price
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      (price) => {
        return target.applyDiscount(price, 0) === price;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_003", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_003",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_004: 100% discount results in zero price
// Category: boundary
// Evidence: 100% discount = free; price * (1 - 100/100) = 0
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      (price) => {
        return target.applyDiscount(price, 100) === 0;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_004", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_004",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_005: Total of empty array is zero
// Category: boundary
// Evidence: @param prices - Array of item prices; empty cart costs nothing
try {
  const __result = target.calculateTotal([]) === 0;
  if (!__result) throw new Error("Assertion failed: target.calculateTotal([]) === 0");
  console.log(JSON.stringify({ propertyId: "prop_005", status: "passed", iterations: 1 }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_005",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_006: Total of single-item array equals the item
// Category: boundary
// Evidence: Single item total = the item itself
try {
  fc.assert(
    fc.property(
      fc.double({ min: 0, max: 10000, noNaN: true }),
      (price) => {
        return target.calculateTotal([price]) === price;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_006", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_006",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_007: Total is non-negative when all prices are non-negative
// Category: boundary
// Evidence: @returns Total sum; sum of non-negative numbers is non-negative
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 20 }),
      (prices) => {
        return prices.every(p => p >= 0) ? target.calculateTotal(prices) >= 0 : true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_007", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_007",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_008: Output always has exactly 2 decimal places
// Category: type-preservation
// Evidence: @returns Formatted string like "99.99"; toFixed(2) always gives 2 decimals
try {
  fc.assert(
    fc.property(
      fc.double({ min: -10000, max: 10000, noNaN: true }),
      (price) => {
        return /^-?\d+\.\d{2}$/.test(target.formatPrice(price));
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_008", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_008",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_009: Parsing formatted price back gives approximately the original
// Category: roundtrip
// Evidence: Formatted price should round-trip within rounding tolerance
try {
  fc.assert(
    fc.property(
      fc.double({ min: -10000, max: 10000, noNaN: true }),
      (price) => {
        return Math.abs(parseFloat(target.formatPrice(price)) - price) < 0.01;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_009", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_009",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}
