// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/sort-utils.ts
// Generated: 2026-03-27T00:44:30.679Z

const fc = require("C:/Users/allenenli/claude-code-projects/propcheck/node_modules/fast-check/lib/cjs/fast-check.js");
const target = require("../../test-fixtures/typescript/sort-utils.ts");

const numRuns = 1000;

// prop_001: Output length equals input length
// Category: conservation
// Evidence: Sorting should not add or remove elements
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 50 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return target.sortNumbers(arr).length === arr.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_002: Output is monotonically non-decreasing
// Category: monotonic
// Evidence: @returns New sorted array; ascending order
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 50 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return target.sortNumbers(arr).every((v, i, a) => i === 0 || a[i-1] <= v);
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_003: Sorting is idempotent
// Category: idempotent
// Evidence: Sorting an already sorted array should be a no-op
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 30 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return JSON.stringify(target.sortNumbers(target.sortNumbers(arr))) === JSON.stringify(target.sortNumbers(arr));
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_003", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_003",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_004: Does not mutate the input array
// Category: boundary
// Evidence: Uses [...arr].sort() — spread creates a copy
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 20 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return (() => { const copy = [...arr]; target.sortNumbers(arr); return JSON.stringify(arr) === JSON.stringify(copy); })();
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_004", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_004",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_005: Output has no duplicate elements
// Category: boundary
// Evidence: Uses new Set() which removes duplicates
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 50 }),
      (arr) => {
        const result = target.unique(arr);
        return new Set(target.unique(arr)).size === target.unique(arr).length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_005", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_005",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_006: Output length is at most input length
// Category: conservation
// Evidence: Removing duplicates can only reduce or maintain length
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 50 }),
      (arr) => {
        const result = target.unique(arr);
        return target.unique(arr).length <= arr.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_006", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_006",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_007: Unique is idempotent
// Category: idempotent
// Evidence: Applying unique to already-unique array should be a no-op
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 30 }),
      (arr) => {
        const result = target.unique(arr);
        return JSON.stringify(target.unique(target.unique(arr))) === JSON.stringify(target.unique(arr));
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_007", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_007",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_008: Output length equals sum of input lengths
// Category: conservation
// Evidence: Merge should include all elements from both arrays
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 30 }),
      fc.array(fc.integer(), { maxLength: 30 }),
      (a, b) => {
        const result = target.mergeSorted(a, b);
        return target.mergeSorted(a, b).length === a.length + b.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_008", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_008",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_009: Output is sorted when both inputs are sorted
// Category: monotonic
// Evidence: @param a - First sorted array; @param b - Second sorted array; result should be sorted
try {
  fc.assert(
    fc.property(
      fc.array(fc.integer(), { maxLength: 20 }),
      fc.array(fc.integer(), { maxLength: 20 }),
      (a, b) => {
        const result = target.mergeSorted(a, b);
        return (() => { const sa = [...a].sort((x,y) => x-y); const sb = [...b].sort((x,y) => x-y); return target.mergeSorted(sa, sb).every((v, i, r) => i === 0 || r[i-1] <= v); })();
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_009", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_009",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}
