// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/sort-utils.ts
// Generated: 2026-03-26T14:19:58.928Z

const fc = require("C:/Users/allenenli/claude-code-projects/propcheck/node_modules/fast-check/lib/cjs/fast-check.js");
const target = require("../../test-fixtures/typescript/sort-utils.ts");

const numRuns = 100;

// prop_001: Output length equals input length
// Category: conservation
// Evidence: sorting should not add or remove elements
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 100 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return target.sortNumbers(arr).length === arr.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_002: Output is monotonically non-decreasing
// Category: monotonic
// Evidence: sorted output should be in ascending order
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 100 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return target.sortNumbers(arr).every((v, i, a) => i === 0 || a[i-1] <= v);
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_003: Sorting is idempotent
// Category: idempotent
// Evidence: sorting an already sorted array should give the same result
try {
  fc.assert(
    fc.property(
      fc.array(fc.double({ noNaN: true }), { maxLength: 50 }),
      (arr) => {
        const result = target.sortNumbers(arr);
        return JSON.stringify(target.sortNumbers(target.sortNumbers(arr))) === JSON.stringify(target.sortNumbers(arr));
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_003", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_003",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}
