// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/string-utils.ts
// Generated: 2026-03-27T00:44:48.795Z

const fc = require("C:/Users/allenenli/claude-code-projects/propcheck/node_modules/fast-check/lib/cjs/fast-check.js");
const target = require("../../test-fixtures/typescript/string-utils.ts");

const numRuns = 1000;

// prop_001: Reversing twice returns original
// Category: roundtrip
// Evidence: Reverse is its own inverse: reverse(reverse(x)) === x
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 100 }),
      (str) => {
        const result = target.reverseString(str);
        return target.reverseString(target.reverseString(str)) === str;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_002: Length is preserved after reversing
// Category: conservation
// Evidence: Reversing characters does not change count
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 100 }),
      (str) => {
        const result = target.reverseString(str);
        return target.reverseString(str).length === str.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_003: First character becomes last character
// Category: metamorphic
// Evidence: Reversing puts first element at the end
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 50 }),
      (str) => {
        const result = target.reverseString(str);
        return str.length === 0 || target.reverseString(str)[str.length - 1] === str[0];
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_003", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_003",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_004: Output length never exceeds maxLen
// Category: boundary
// Evidence: @param maxLen - Maximum length; result should respect this limit
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 200 }),
      fc.integer({ min: 3, max: 200 }),
      (str, maxLen) => {
        const result = target.truncate(str, maxLen);
        return target.truncate(str, maxLen).length <= maxLen;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_004", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_004",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_005: Short strings are returned unchanged
// Category: boundary
// Evidence: if (str.length <= maxLen) return str — code returns unchanged
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 50 }),
      fc.integer({ min: 3, max: 100 }),
      (str, maxLen) => {
        const result = target.truncate(str, maxLen);
        return str.length <= maxLen ? target.truncate(str, maxLen) === str : true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_005", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_005",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_006: Truncated strings end with ellipsis
// Category: type-preservation
// Evidence: return str.slice(0, maxLen - 3) + '...' — adds ellipsis
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 200 }),
      fc.integer({ min: 3, max: 100 }),
      (str, maxLen) => {
        const result = target.truncate(str, maxLen);
        return str.length > maxLen ? target.truncate(str, maxLen).endsWith('...') : true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_006", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_006",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_007: Empty string is a palindrome
// Category: boundary
// Evidence: Empty string reversed equals itself
try {
  fc.assert(
    fc.property(
      () => {
        const result = target.isPalindrome();
        return target.isPalindrome('') === true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_007", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_007",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_008: Single characters are palindromes
// Category: boundary
// Evidence: Any single character reads the same forwards and backwards
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 1 }),
      (str) => {
        const result = target.isPalindrome(str);
        return target.isPalindrome(str) === true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_008", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_008",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_009: Concatenating a string with its reverse is always a palindrome
// Category: metamorphic
// Evidence: str + reverse(str) is always a palindrome by construction
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 20 }),
      (str) => {
        const result = target.isPalindrome(str);
        return target.isPalindrome(str + str.split('').reverse().join('')) === true;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_009", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_009",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}
