// Auto-generated by propcheck — do not edit manually
// Target: C:/Users/allenenli/claude-code-projects/propcheck/test-fixtures/typescript/string-utils.ts
// Generated: 2026-03-26T15:32:52.119Z

const fc = require("C:/Users/allenenli/claude-code-projects/propcheck/node_modules/fast-check/lib/cjs/fast-check.js");
const target = require("../../test-fixtures/typescript/string-utils.ts");

const numRuns = 1000;

// prop_001: Reversing twice returns original
// Category: roundtrip
// Evidence: reverse is its own inverse
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 100 }),
      (str) => {
        const result = target.reverseString(str);
        return target.reverseString(target.reverseString(str)) === str;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_001", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_001",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}

// prop_002: Length is preserved after reversing
// Category: conservation
// Evidence: reversing should not change the length
try {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 100 }),
      (str) => {
        const result = target.reverseString(str);
        return target.reverseString(str).length === str.length;
      }
    ),
    { numRuns }
  );
  console.log(JSON.stringify({ propertyId: "prop_002", status: "passed", iterations: numRuns }));
} catch (e) {
  // Parse counterexample from fast-check error message
  let counterexample = null;
  let shrinkSteps = 0;
  const msg = e.message ?? String(e);
  const ceMatch = msg.match(/Counterexample: (\[.*?\])/);
  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }
  const shrinkMatch = msg.match(/Shrunk (\d+) time/);
  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }
  console.log(JSON.stringify({
    propertyId: "prop_002",
    status: "failed",
    counterexample,
    errorMessage: msg,
    shrinkSteps
  }));
}
