/**
 * fast-check code generator — converts PropertyDefinition[] to executable test file.
 *
 * Generates .propcheck/tests/module.fc.ts with fast-check assertions.
 */

import type { PropertyDefinition, GeneratorSpec, RunConfig } from "@propcheck/common";
import { toForwardSlash } from "@propcheck/common";
import * as path from "node:path";

/**
 * Map a GeneratorSpec to a fast-check Arbitrary expression.
 */
function mapGenerator(spec: GeneratorSpec): string {
  const c = spec.constraints ?? {};

  switch (spec.type) {
    case "integer":
      if (c.min !== undefined || c.max !== undefined) {
        const parts: string[] = [];
        if (c.min !== undefined) parts.push(`min: ${c.min}`);
        if (c.max !== undefined) parts.push(`max: ${c.max}`);
        return `fc.integer({ ${parts.join(", ")} })`;
      }
      return "fc.integer()";

    case "float":
    case "number":
      if (c.min !== undefined || c.max !== undefined) {
        const parts: string[] = [];
        if (c.min !== undefined) parts.push(`min: ${c.min}`);
        if (c.max !== undefined) parts.push(`max: ${c.max}`);
        return `fc.double({ ${parts.join(", ")}, noNaN: true })`;
      }
      return "fc.double({ noNaN: true })";

    case "string":
      if (c.maxLength !== undefined) {
        return `fc.string({ maxLength: ${c.maxLength} })`;
      }
      return "fc.string()";

    case "boolean":
      return "fc.boolean()";

    case "array": {
      const element = c.element ? mapGenerator({ type: String(c.element) }) : "fc.anything()";
      const maxLen = c.maxLength ? `, { maxLength: ${c.maxLength} }` : "";
      return `fc.array(${element}${maxLen})`;
    }

    case "record":
      return "fc.dictionary(fc.string(), fc.anything())";

    default:
      return "fc.anything()";
  }
}

/**
 * Generate a fast-check test file for the given properties.
 */
export function generateFastCheckTest(
  properties: readonly PropertyDefinition[],
  targetFile: string,
  testDir: string,
  config: RunConfig,
): { readonly content: string; readonly fileName: string } {
  const relativeImport = toForwardSlash(
    path.relative(testDir, targetFile),
  ).replace(/\.(ts|tsx|js|jsx)$/, "");

  const importPath = relativeImport.startsWith(".") ? relativeImport : `./${relativeImport}`;

  // Collect unique function names for imports
  const functionNames = [...new Set(properties.map((p) => p.targetFunction.split(".").pop()!))];

  // Try to resolve fast-check absolute path for reliable loading
  let fcRequire = `require("fast-check")`;
  try {
    const fcPath = require.resolve("fast-check");
    fcRequire = `require(${JSON.stringify(toForwardSlash(fcPath))})`;
  } catch {
    // Fall back to relative require — user must have fast-check installed
  }

  const lines: string[] = [];

  // Header
  lines.push(`// Auto-generated by propcheck — do not edit manually`);
  lines.push(`// Target: ${toForwardSlash(targetFile)}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`const fc = ${fcRequire};`);
  lines.push(`const target = require("${importPath}");`);
  lines.push(``);
  lines.push(`const numRuns = ${config.iterations};`);
  lines.push(``);

  // Generate test for each property
  for (const prop of properties) {
    const funcName = prop.targetFunction.split(".").pop()!;
    const generators = Object.entries(prop.generators);
    const arbNames = generators.map(([name]) => name);
    const arbExprs = generators.map(([, spec]) => mapGenerator(spec));

    lines.push(`// ${prop.id}: ${prop.description}`);
    lines.push(`// Category: ${prop.category}`);
    lines.push(`// Evidence: ${prop.evidence}`);
    lines.push(`try {`);
    lines.push(`  fc.assert(`);
    lines.push(`    fc.property(`);

    // Add arbitraries
    for (let i = 0; i < arbExprs.length; i++) {
      const comma = i < arbExprs.length - 1 ? "," : ",";
      lines.push(`      ${arbExprs[i]}${comma}`);
    }

    // Add predicate
    lines.push(`      (${arbNames.join(", ")}) => {`);
    lines.push(`        const result = target.${funcName}(${arbNames.join(", ")});`);
    // Replace bare function calls with target.funcName in assertion
    const assertion = prop.assertion.replace(
      new RegExp(`\\b${funcName}\\(`, "g"),
      `target.${funcName}(`,
    );
    lines.push(`        return ${assertion};`);
    lines.push(`      }`);
    lines.push(`    ),`);
    lines.push(`    { numRuns${config.seed !== undefined ? `, seed: ${config.seed}` : ""} }`);
    lines.push(`  );`);
    lines.push(`  console.log(JSON.stringify({ propertyId: "${prop.id}", status: "passed", iterations: numRuns }));`);
    lines.push(`} catch (e) {`);
    lines.push(`  const counterexample = e.counterexample ?? null;`);
    lines.push(`  console.log(JSON.stringify({`);
    lines.push(`    propertyId: "${prop.id}",`);
    lines.push(`    status: "failed",`);
    lines.push(`    counterexample,`);
    lines.push(`    errorMessage: e.message ?? String(e),`);
    lines.push(`    shrinkSteps: e.numShrinks ?? 0`);
    lines.push(`  }));`);
    lines.push(`}`);
    lines.push(``);
  }

  const baseName = path.basename(targetFile, path.extname(targetFile));
  const fileName = `${baseName}.fc.js`;

  return {
    content: lines.join("\n"),
    fileName,
  };
}
