/**
 * fast-check code generator — converts PropertyDefinition[] to executable test file.
 *
 * Generates .propcheck/tests/module.fc.ts with fast-check assertions.
 */

import type { PropertyDefinition, GeneratorSpec, RunConfig } from "@propcheck/common";
import { toForwardSlash } from "@propcheck/common";
import * as path from "node:path";

/** Strip newlines and limit length for safe embedding in code comments. */
function toSafeComment(s: string): string {
  return s.replace(/[\r\n\u2028\u2029]/g, " ").slice(0, 200);
}

/**
 * Map a GeneratorSpec to a fast-check Arbitrary expression.
 */
function mapGenerator(spec: GeneratorSpec): string {
  const c = spec.constraints ?? {};

  switch (spec.type) {
    case "integer":
      if (c.min !== undefined || c.max !== undefined) {
        const parts: string[] = [];
        if (c.min !== undefined) parts.push(`min: ${Number(c.min)}`);
        if (c.max !== undefined) parts.push(`max: ${Number(c.max)}`);
        return `fc.integer({ ${parts.join(", ")} })`;
      }
      return "fc.integer()";

    case "float":
    case "number":
      if (c.min !== undefined || c.max !== undefined) {
        const parts: string[] = [];
        if (c.min !== undefined) parts.push(`min: ${Number(c.min)}`);
        if (c.max !== undefined) parts.push(`max: ${Number(c.max)}`);
        return `fc.double({ ${parts.join(", ")}, noNaN: true, noDefaultInfinity: true })`;
      }
      // Default to non-negative range — most business-domain values (prices,
      // counts, percentages) are non-negative, and unconstrained doubles that
      // span -1.7e308..+1.7e308 cause false failures far more often than they
      // find real bugs.
      return "fc.double({ min: 0, noNaN: true, noDefaultInfinity: true })";

    case "string":
      if (c.maxLength !== undefined) {
        return `fc.string({ maxLength: ${Number(c.maxLength)} })`;
      }
      return "fc.string()";

    case "boolean":
      return "fc.boolean()";

    case "array": {
      const element = c.element ? mapGenerator({ type: String(c.element).replace(/[^a-zA-Z0-9_]/g, "") }) : "fc.anything()";
      const maxLen = c.maxLength ? `, { maxLength: ${Number(c.maxLength)} }` : "";
      return `fc.array(${element}${maxLen})`;
    }

    case "record":
      return "fc.dictionary(fc.string(), fc.anything())";

    default:
      return "fc.anything()";
  }
}

/**
 * Generate a fast-check test file for the given properties.
 */
export function generateFastCheckTest(
  properties: readonly PropertyDefinition[],
  targetFile: string,
  testDir: string,
  config: RunConfig,
): { readonly content: string; readonly fileName: string } {
  const relativeImport = toForwardSlash(
    path.relative(testDir, targetFile),
  ).replace(/\.(ts|tsx|js|jsx)$/, "");

  // Keep the file extension for TypeScript files so Node.js --experimental-strip-types
  // can resolve them. For JS files, strip the extension per Node.js convention.
  let importPathStr: string;
  if (targetFile.endsWith(".ts") || targetFile.endsWith(".tsx")) {
    // Keep .ts extension — Node with --experimental-strip-types needs it
    importPathStr = toForwardSlash(path.relative(testDir, targetFile));
    if (!importPathStr.startsWith(".")) importPathStr = `./${importPathStr}`;
  } else {
    const noExt = relativeImport.startsWith(".") ? relativeImport : `./${relativeImport}`;
    importPathStr = noExt;
  }

  // Collect unique function names for imports
  const functionNames = [...new Set(properties.map((p) => p.targetFunction.split(".").pop()!))];

  // Try to resolve fast-check absolute path for reliable loading
  let fcRequire = `require("fast-check")`;
  try {
    const fcPath = require.resolve("fast-check");
    fcRequire = `require(${JSON.stringify(toForwardSlash(fcPath))})`;
  } catch {
    // Fall back to relative require — user must have fast-check installed
  }

  const lines: string[] = [];

  // Header
  lines.push(`// Auto-generated by propcheck — do not edit manually`);
  lines.push(`// Target: ${toForwardSlash(targetFile)}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`const fc = ${fcRequire};`);
  lines.push(`const target = require("${importPathStr}");`);
  lines.push(``);
  lines.push(`const numRuns = ${config.iterations};`);
  lines.push(``);

  // Generate test for each property
  for (const prop of properties) {
    const funcName = prop.targetFunction.split(".").pop()!;
    const generators = Object.entries(prop.generators);
    const arbNames = generators.map(([name]) => name);
    const arbExprs = generators.map(([, spec]) => mapGenerator(spec));

    // Replace bare function calls with target.funcName in assertion.
    // Also replace calls to any other imported function names from the target module.
    let assertion = prop.assertion.replace(
      new RegExp(`\\b${funcName}\\(`, "g"),
      `target.${funcName}(`,
    );

    // Rewrite array-literal arguments that embed generator parameter names.
    // e.g. "calculateTotal([price])" → build the array in the predicate body.
    // We detect patterns like funcName([paramName, ...]) and leave them as-is
    // since JavaScript `[paramName]` inside a lambda is valid — the parameter
    // names from fc.property destructuring are in scope.  No rewrite needed
    // for correctness, but we ensure all referenced names actually exist as
    // generator parameters to catch LLM hallucinated variable names.
    for (const varName of assertion.match(/\b[a-zA-Z_]\w*\b/g) ?? []) {
      if (
        varName !== funcName &&
        varName !== "target" &&
        varName !== "true" &&
        varName !== "false" &&
        varName !== "null" &&
        varName !== "undefined" &&
        varName !== "Math" &&
        varName !== "Number" &&
        varName !== "String" &&
        varName !== "Array" &&
        varName !== "JSON" &&
        varName !== "Object" &&
        varName !== "NaN" &&
        varName !== "Infinity" &&
        !arbNames.includes(varName) &&
        !functionNames.includes(varName)
      ) {
        // Unknown variable in assertion — likely references another function
        // from the target module.  Qualify with target.
        assertion = assertion.replace(
          new RegExp(`\\b${varName}\\(`, "g"),
          `target.${varName}(`,
        );
      }
    }

    lines.push(`// ${prop.id}: ${toSafeComment(prop.description)}`);
    lines.push(`// Category: ${toSafeComment(prop.category)}`);
    lines.push(`// Evidence: ${toSafeComment(prop.evidence)}`);
    lines.push(`try {`);

    if (generators.length === 0) {
      // Zero-parameter assertion — wrap with a dummy fc.constant(null) arbitrary
      // so all properties go through the same fc.assert pathway.  fast-check's
      // fc.property() requires at least 1 arbitrary.
      lines.push(`  fc.assert(`);
      lines.push(`    fc.property(`);
      lines.push(`      fc.constant(null),`);
      lines.push(`      () => {`);
      lines.push(`        return ${assertion};`);
      lines.push(`      }`);
      lines.push(`    ),`);
      lines.push(`    { numRuns: 1 }`);
      lines.push(`  );`);
      lines.push(`  console.log(JSON.stringify({ propertyId: "${prop.id}", status: "passed", iterations: 1 }));`);
    } else {
      lines.push(`  fc.assert(`);
      lines.push(`    fc.property(`);

      // Add arbitraries
      for (let i = 0; i < arbExprs.length; i++) {
        lines.push(`      ${arbExprs[i]},`);
      }

      // Add predicate
      lines.push(`      (${arbNames.join(", ")}) => {`);
      lines.push(`        return ${assertion};`);
      lines.push(`      }`);
      lines.push(`    ),`);
      lines.push(`    { numRuns${config.seed !== undefined ? `, seed: ${config.seed}` : ""} }`);
      lines.push(`  );`);
      lines.push(`  console.log(JSON.stringify({ propertyId: "${prop.id}", status: "passed", iterations: numRuns }));`);
    }
    lines.push(`} catch (e) {`);
    lines.push(`  // Parse counterexample from fast-check error message`);
    lines.push(`  let counterexample = null;`);
    lines.push(`  let shrinkSteps = 0;`);
    lines.push(`  const msg = e.message ?? String(e);`);
    lines.push(`  const ceMatch = msg.match(/Counterexample: (\\[.*?\\])/);`);
    lines.push(`  if (ceMatch) { try { counterexample = JSON.parse(ceMatch[1]); } catch {} }`);
    lines.push(`  const shrinkMatch = msg.match(/Shrunk (\\d+) time/);`);
    lines.push(`  if (shrinkMatch) { shrinkSteps = parseInt(shrinkMatch[1], 10); }`);
    lines.push(`  console.log(JSON.stringify({`);
    lines.push(`    propertyId: "${prop.id}",`);
    lines.push(`    status: "failed",`);
    lines.push(`    counterexample,`);
    lines.push(`    errorMessage: msg,`);
    lines.push(`    shrinkSteps`);
    lines.push(`  }));`);
    lines.push(`}`);
    lines.push(``);
  }

  const baseName = path.basename(targetFile, path.extname(targetFile));
  const fileName = `${baseName}.fc.js`;

  return {
    content: lines.join("\n"),
    fileName,
  };
}
