/**
 * Hypothesis code generator — converts PropertyDefinition[] to Python test file.
 *
 * Generates .propcheck/tests/module.hyp.py with Hypothesis strategies.
 */

import type { PropertyDefinition, GeneratorSpec, RunConfig } from "@propcheck/common";
import { toForwardSlash } from "@propcheck/common";
import * as path from "node:path";

/** Strip newlines and limit length for safe embedding in code comments. */
function toSafeComment(s: string): string {
  return s.replace(/[\r\n\u2028\u2029]/g, " ").slice(0, 200);
}

/**
 * Map a GeneratorSpec to a Hypothesis strategy expression.
 */
function mapStrategy(spec: GeneratorSpec): string {
  const c = spec.constraints ?? {};

  switch (spec.type) {
    case "integer":
    case "int": {
      const parts: string[] = [];
      if (c.min !== undefined) parts.push(`min_value=${Number(c.min)}`);
      if (c.max !== undefined) parts.push(`max_value=${Number(c.max)}`);
      return parts.length > 0 ? `st.integers(${parts.join(", ")})` : "st.integers()";
    }

    case "float":
    case "number": {
      const parts: string[] = ["allow_nan=False", "allow_infinity=False"];
      if (c.min !== undefined) parts.push(`min_value=${Number(c.min)}`);
      if (c.max !== undefined) parts.push(`max_value=${Number(c.max)}`);
      return `st.floats(${parts.join(", ")})`;
    }

    case "string":
    case "str": {
      if (c.maxLength !== undefined) {
        return `st.text(max_size=${Number(c.maxLength)})`;
      }
      return "st.text()";
    }

    case "boolean":
    case "bool":
      return "st.booleans()";

    case "array":
    case "list": {
      const element = c.element ? mapStrategy({ type: String(c.element).replace(/[^a-zA-Z0-9_]/g, "") }) : "st.integers()";
      const maxLen = c.maxLength ? `, max_size=${Number(c.maxLength)}` : "";
      return `st.lists(${element}${maxLen})`;
    }

    case "dict":
    case "record":
      return "st.dictionaries(st.text(min_size=1, max_size=10), st.integers())";

    default:
      return "st.integers()";
  }
}

/**
 * Generate a Hypothesis test file for the given properties.
 */
export function generateHypothesisTest(
  properties: readonly PropertyDefinition[],
  targetFile: string,
  testsDir: string,
  config: RunConfig,
): { readonly content: string; readonly fileName: string } {
  // Compute relative import: from the test dir to the target module
  const targetDir = path.dirname(targetFile);
  const moduleName = path.basename(targetFile, path.extname(targetFile));

  // Build sys.path manipulation for reliable import
  const relTargetDir = toForwardSlash(path.relative(testsDir, targetDir));

  const lines: string[] = [];

  // Header
  lines.push(`# Auto-generated by propcheck — do not edit manually`);
  lines.push(`# Target: ${toForwardSlash(targetFile)}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`import sys`);
  lines.push(`import os`);
  lines.push(`import json`);
  lines.push(`from pathlib import Path`);
  lines.push(``);
  lines.push(`# Add target directory to Python path`);
  lines.push(`sys.path.insert(0, str(Path(__file__).parent / "${relTargetDir}"))`);
  lines.push(``);
  lines.push(`from hypothesis import given, settings, assume`);
  lines.push(`from hypothesis import strategies as st`);
  lines.push(`import ${moduleName} as target`);
  lines.push(``);
  lines.push(`MAX_EXAMPLES = ${config.iterations}`);
  lines.push(``);

  // Generate test for each property
  for (const prop of properties) {
    const funcName = prop.targetFunction.split(".").pop()!;
    const generators = Object.entries(prop.generators);

    // Build @given decorator args
    const givenArgs = generators
      .map(([name, spec]) => `${name}=${mapStrategy(spec)}`)
      .join(", ");

    const paramNames = generators.map(([name]) => name).join(", ");

    // Replace bare function calls with target.funcName
    let assertion = prop.assertion.replace(
      new RegExp(`\\b${funcName}\\(`, "g"),
      `target.${funcName}(`,
    );

    // Translate JavaScript syntax to Python
    assertion = assertion.replace(/===/g, "==");   // strict equality → Python equality
    assertion = assertion.replace(/!==/g, "!=");   // strict inequality
    assertion = assertion.replace(/\btrue\b/g, "True");
    assertion = assertion.replace(/\bfalse\b/g, "False");
    assertion = assertion.replace(/\bnull\b/g, "None");
    assertion = assertion.replace(/\bundefined\b/g, "None");
    assertion = assertion.replace(/\.length\b/g, ".__len__()");  // arr.length → len(arr)

    lines.push(`# ${prop.id}: ${toSafeComment(prop.description)}`);
    lines.push(`# Category: ${toSafeComment(prop.category)}`);
    lines.push(`# Evidence: ${toSafeComment(prop.evidence)}`);
    lines.push(`def test_${prop.id}():`);
    lines.push(`    try:`);

    if (generators.length === 0) {
      // Zero-parameter assertion — run as simple assert
      lines.push(`        assert ${assertion}`);
    } else {
      lines.push(`        @given(${givenArgs})`);
      lines.push(`        @settings(max_examples=MAX_EXAMPLES)`);
      lines.push(`        def inner(${paramNames}):`);
      lines.push(`            assert ${assertion}`);
      lines.push(`        inner()`);
    }

    lines.push(`        print(json.dumps({"propertyId": "${prop.id}", "status": "passed", "iterations": ${generators.length === 0 ? 1 : "MAX_EXAMPLES"}}))`);
    lines.push(`    except AssertionError as e:`);
    lines.push(`        print(json.dumps({"propertyId": "${prop.id}", "status": "failed", "counterexample": str(e), "errorMessage": str(e), "shrinkSteps": 0}))`);
    lines.push(`    except Exception as e:`);
    lines.push(`        msg = str(e)`);
    lines.push(`        print(json.dumps({"propertyId": "${prop.id}", "status": "failed", "counterexample": msg[:200], "errorMessage": msg[:200], "shrinkSteps": 0}))`);
    lines.push(``);
  }

  // Run all tests
  lines.push(`if __name__ == "__main__":`);
  for (const prop of properties) {
    lines.push(`    test_${prop.id}()`);
  }

  const fileName = `${moduleName}.hyp.py`;

  return {
    content: lines.join("\n"),
    fileName,
  };
}
